export default {
    "inventory": [
        { "title": "Kill La Kill vol. 1", "author": "Kazuki, Nakashima, TRIGGER, Akizuki, Ryo", "price": "$7.50", "imgsrc": "https://kill-la-kill.fandom.com/wiki/File:KLKMV1.jpg" },
        { "title": "Kill La Kill vol. 2", "author": "Kazuki, Nakashima, TRIGGER, Akizuki, Ryo", "price": "$7.50", "imgsrc": "https://kill-la-kill.fandom.com/wiki/File:KLKMV2.jpg" },
        { "title": "Kill La Kill vol. 3", "author": "Kazuki, Nakashima, TRIGGER, Akizuki, Ryo", "price": "$7.50", "imgsrc": "https://kill-la-kill.fandom.com/wiki/File:KLKMV3.jpg" },
        { "title": "Komi Can't Communicate vol. 1", "author": "Tomohito Oda", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/komisan-wa-komyushou-desu/images/d/d4/Volume_1_%28English%29.png/revision/latest/scale-to-width-down/160?cb=20210623002036" },
        { "title": "Komi Can't Communicate vol. 2", "author": "Tomohito Oda", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/komisan-wa-komyushou-desu/images/7/75/Komi_San_Volume_2_EN.png/revision/latest/scale-to-width-down/160?cb=20200218231100" },
        { "title": "Komi Can't Communicate vol. 3", "author": "Tomohito Oda", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/komisan-wa-komyushou-desu/images/8/83/Komi_San_Volume_3_EN.png/revision/latest/scale-to-width-down/160?cb=20200218231114" },
        { "title": "Komi Can't Communicate vol. 4", "author": "Tomohito Oda", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/komisan-wa-komyushou-desu/images/e/e4/Volume_4_%28English%29.png/revision/latest/scale-to-width-down/160?cb=20210622152944" },
        { "title": "Higurashi When They Cry vol. 1", "author": "Ryukishi07, Suzuragi, Hōjō, Suzuki, Tonogai, Momoyama, Kitō, Mimori, Kagesaki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/whentheycry/images/4/48/Minagoroshi-hen_1.jpg/revision/latest/scale-to-width-down/200?cb=20130105162755" },
        { "title": "Higurashi When They Cry vol. 2", "author": "Ryukishi07, Suzuragi, Hōjō, Suzuki, Tonogai, Momoyama, Kitō, Mimori, Kagesaki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/whentheycry/images/1/1d/Minagoroshi-hen_2.jpg/revision/latest/scale-to-width-down/200?cb=20130105162841" },
        { "title": "Higurashi When They Cry vol. 3", "author": "Ryukishi07, Suzuragi, Hōjō, Suzuki, Tonogai, Momoyama, Kitō, Mimori, Kagesaki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/whentheycry/images/2/27/Minagoroshi-hen_3.jpg/revision/latest/scale-to-width-down/200?cb=20130105162924" },
        { "title": "Future Diary vol. 1", "author": "Sakae Esuno", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/futurediary/images/0/0e/Volume_1.png/revision/latest/scale-to-width-down/200?cb=20151019201802" },
        { "title": "Future Diary vol. 2", "author": "Sakae Esuno", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/futurediary/images/2/2f/Volume_2.png/revision/latest/scale-to-width-down/200?cb=20151019201859" },
        { "title": "Future Diary vol. 3", "author": "Sakae Esuno", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/futurediary/images/7/75/Volume_3.png/revision/latest/scale-to-width-down/200?cb=20151019202118" },
        { "title": "Future Diary vol. 4", "author": "Sakae Esuno", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/futurediary/images/3/31/Volume_4.png/revision/latest/scale-to-width-down/200?cb=20151019202524" },
        { "title": "Future Diary vol. 5", "author": "Sakae Esuno", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/futurediary/images/8/8a/Volume_5.png/revision/latest/scale-to-width-down/200?cb=20151019203202" },
        { "title": "Future Diary vol. 6", "author": "Sakae Esuno", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/futurediary/images/f/fb/Volume_6.png/revision/latest/scale-to-width-down/200?cb=20151019203325" },
        { "title": "Danganronpa", "author": "Kazutaka Kodaka", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/danganronpa/images/6/6d/Manga_Cover_-_Danganronpa_The_Animation_Volume_1_%28Front%29_%28English%29.jpg/revision/latest?cb=20170925200824" },
        { "title": "Soul Eater vol. 1", "author": "Atsushi Ohkubo", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/souleater/images/6/6a/Volume_01.jpg/revision/latest?cb=20130201200303" },
        { "title": "Soul Eater vol. 2", "author": "Atsushi Ohkubo", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/souleater/images/1/17/Volume_02.jpg/revision/latest?cb=20130201200336" },
        { "title": "Soul Eater vol. 3", "author": "Atsushi Ohkubo", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/souleater/images/2/26/Volume_03.jpg/revision/latest?cb=20130201200409" },
        { "title": "Soul Eater vol. 4", "author": "Atsushi Ohkubo", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/souleater/images/3/3c/Volume_04.jpg/revision/latest?cb=20130201200448" },
        { "title": "Prison School vol. 1", "author": "Akira Hiramoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/prison-school/images/6/6a/Volume_01.jpg/revision/latest?cb=20150826125330" },
        { "title": "Prison School vol. 2", "author": "Akira Hiramoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/prison-school/images/1/17/Volume_02.jpg/revision/latest?cb=20150725090517" },
        { "title": "Prison School vol. 3", "author": "Akira Hiramoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/prison-school/images/2/26/Volume_03.jpg/revision/latest?cb=20160628152812" },
        { "title": "Prison School vol. 4", "author": "Akira Hiramoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/prison-school/images/3/3c/Volume_04.jpg/revision/latest?cb=20160628170813" },
        { "title": "Prison School vol. 5", "author": "Akira Hiramoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/prison-school/images/f/fd/Volume_05.jpg/revision/latest?cb=20150826115758" },
        { "title": "The Devil Is a Part-Timer! vol. 1", "author": "Wagahara, Oniku(029)", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/hataraku/images/4/4e/HatMao_Volume_1.jpg/revision/latest?cb=20201120110232" },
        { "title": "The Devil Is a Part-Timer! vol. 2", "author": "Wagahara, Oniku(029)", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/hataraku/images/0/0f/HatamaoV2.jpg/revision/latest?cb=20150827033147" },
        { "title": "The Devil Is a Part-Timer! vol. 3", "author": "Wagahara, Oniku(029)", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/hataraku/images/1/15/Volume_3_English.png/revision/latest?cb=20150925012746" },
        { "title": "The Devil Is a Part-Timer! vol. 4", "author": "Wagahara, Oniku(029)", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/hataraku/images/d/d5/Volume_4_English.png/revision/latest?cb=20160226064936" },
        { "title": "Shimoneta vol. 1", "author": "Akagi, Shimotsuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/shimoneta-to-lu/images/c/ca/Shimoseka-2.jpg/revision/latest/scale-to-width-down/165?cb=20150728075609" },
        { "title": "Shimoneta vol. 2", "author": "Akagi, Shimotsuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/shimoneta-to-lu/images/8/89/Shimoneta-to-Iu-Gainen-ga-Sonzai-Shinai-Taikutsu-na-Sekai.jpg/revision/latest/scale-to-width-down/165?cb=20231021055341" },
        { "title": "Shimoneta vol. 3", "author": "Akagi, Shimotsuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/shimoneta-to-lu/images/e/e4/Shimoneta_v03_cover.jpg/revision/latest/scale-to-width-down/165?cb=20231214184739" },
        { "title": "Shimoneta vol. 4", "author": "Akagi, Shimotsuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/shimoneta-to-lu/images/4/49/Shimoneta_v04_cover.jpg/revision/latest/scale-to-width-down/165?cb=20231214184849" },
        { "title": "Shimoneta vol. 5", "author": "Akagi, Shimotsuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/shimoneta-to-lu/images/8/80/Shimoneta_v05_cover.jpg/revision/latest/scale-to-width-down/165?cb=20231209222048" },
        { "title": "Shimoneta vol. 6", "author": "Akagi, Shimotsuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/shimoneta-to-lu/images/0/0c/Shimoneta_v06_cover.jpg/revision/latest/scale-to-width-down/165?cb=20231209233225" },
        { "title": "Highschool of the Dead vol. 1", "author": "Satō, Satō", "price": "$7.50", "imgsrc": "https://m.media-amazon.com/images/I/51br3rvm0pL._SY300_.jpg" },
        { "title": "Highschool of the Dead vol. 2", "author": "Satō, Satō", "price": "$7.50", "imgsrc": "https://m.media-amazon.com/images/I/51-3wU1RFpL._SY300_.jpg" },
        { "title": "Highschool of the Dead vol. 3", "author": "Satō, Satō", "price": "$7.50", "imgsrc": "https://m.media-amazon.com/images/I/51ehhWvWoXL._SY300_.jpg" },
        { "title": "Highschool of the Dead vol. 4", "author": "Satō, Satō", "price": "$7.50", "imgsrc": "https://m.media-amazon.com/images/I/51eVs1ibtrL._SY300_.jpg" },
        { "title": "Highschool of the Dead vol. 5", "author": "Satō, Satō", "price": "$7.50", "imgsrc": "https://m.media-amazon.com/images/I/51VyWSZSqXL._SY300_.jpg" },
        { "title": "Highschool of the Dead vol. 6", "author": "Satō, Satō", "price": "$7.50", "imgsrc": "https://m.media-amazon.com/images/I/51nBB4Bh65L._SY300_.jpg" },
        { "title": "Highschool of the Dead vol. 7", "author": "Satō, Satō", "price": "$7.50", "imgsrc": "https://m.media-amazon.com/images/I/51Pbu0TJ5UL._SY300_.jpg" },
        { "title": "Sakamoto Days Vol. 1", "author": "Yuto Suzuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/sakamoto-days/images/0/0f/Volume_01.png/" },
        { "title": "Sakamoto Days Vol. 2", "author": "Yuto Suzuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/sakamoto-days/images/6/68/Volume_02.png/" },
        { "title": "Sakamoto Days Vol. 3", "author": "Yuto Suzuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/sakamoto-days/images/5/5c/Volume_03.png/" },
        { "title": "Sakamoto Days Vol. 4", "author": "Yuto Suzuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/sakamoto-days/images/e/ef/Volume_04.png/" },
        { "title": "Sakamoto Days Vol. 5", "author": "Yuto Suzuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/sakamoto-days/images/c/cf/Volume_05.png/" },
        { "title": "Sakamoto Days Vol. 6", "author": "Yuto Suzuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/sakamoto-days/images/2/2e/Volume_06.png/" },
        { "title": "Sakamoto Days Vol. 7", "author": "Yuto Suzuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/sakamoto-days/images/3/36/Volume_07.png/" },
        { "title": "Sakamoto Days Vol. 8", "author": "Yuto Suzuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/sakamoto-days/images/1/14/Volume_08.png/" },
        { "title": "Sakamoto Days Vol. 9", "author": "Yuto Suzuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/sakamoto-days/images/f/f3/Volume_09.png/" },
        { "title": "Sakamoto Days Vol. 10", "author": "Yuto Suzuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/sakamoto-days/images/6/6b/Volume_10.png/" },
        { "title": "Sakamoto Days Vol. 11", "author": "Yuto Suzuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/sakamoto-days/images/1/1b/Volume_11.png/" },
        { "title": "Sakamoto Days Vol. 12", "author": "Yuto Suzuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/sakamoto-days/images/4/4e/Volume_12.png/" },
        { "title": "Sakamoto Days Vol. 13", "author": "Yuto Suzuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/sakamoto-days/images/b/b6/Volume_13.png/" },
        { "title": "Sakamoto Days Vol. 14", "author": "Yuto Suzuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/sakamoto-days/images/1/17/Volume_14.png/" },
        { "title": "Sakamoto Days Vol. 15", "author": "Yuto Suzuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/sakamoto-days/images/4/4e/Volume_15.png/" },
        { "title": "Sakamoto Days Vol. 16", "author": "Yuto Suzuki", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/sakamoto-days/images/4/45/Volume_16.png/" },
        { "title": "Dandadan Vol. 1", "author": "Yukinobu Tatsu", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/dandadan/images/d/d4/Volume_1_%28English%29.png/" },
        { "title": "Dandadan Vol. 2", "author": "Yukinobu Tatsu", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/dandadan/images/1/15/Volume_2_%28English%29.png/" },
        { "title": "Dandadan Vol. 3", "author": "Yukinobu Tatsu", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/dandadan/images/6/6c/Volume_3_%28English%29.png/" },
        { "title": "Dandadan Vol. 4", "author": "Yukinobu Tatsu", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/dandadan/images/e/e4/Volume_4_%28English%29.png/" },
        { "title": "Dandadan Vol. 5", "author": "Yukinobu Tatsu", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/dandadan/images/8/8a/Volume_5.png/" },
        { "title": "Dandadan Vol. 6", "author": "Yukinobu Tatsu", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/dandadan/images/f/fb/Volume_6.png/" },
        { "title": "Dandadan Vol. 7", "author": "Yukinobu Tatsu", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/dandadan/images/2/24/Volume_7.png/" },
        { "title": "Dandadan Vol. 8", "author": "Yukinobu Tatsu", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/dandadan/images/8/82/Volume_8.png/" },
        { "title": "Dandadan Vol. 9", "author": "Yukinobu Tatsu", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/dandadan/images/7/79/Volume_9.png/" },
        { "title": "Dandadan Vol. 10", "author": "Yukinobu Tatsu", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/dandadan/images/6/6b/Volume_10.png/" },
        { "title": "Dandadan Vol. 11", "author": "Yukinobu Tatsu", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/dandadan/images/1/1b/Volume_11.png/" },
        { "title": "Dandadan Vol. 12", "author": "Yukinobu Tatsu", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/dandadan/images/4/4e/Volume_12.png/" },
        { "title": "Dandadan Vol. 13", "author": "Yukinobu Tatsu", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/dandadan/images/b/b6/Volume_13.png/" },
        { "title": "Dandadan Vol. 14", "author": "Yukinobu Tatsu", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/dandadan/images/1/17/Volume_14.png/" },
        { "title": "Jujutsu Kaisen Vol. 0", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/0/0b/ENG_Volume_0.png/" },
        { "title": "Jujutsu Kaisen Vol. 1", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/e/ea/ENG_Volume_1.png/" },
        { "title": "Jujutsu Kaisen Vol. 2", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/d/d2/ENG_Volume_2.png/" },
        { "title": "Jujutsu Kaisen Vol. 3", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/b/ba/ENG_Volume_3.png/" },
        { "title": "Jujutsu Kaisen Vol. 4", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/2/24/ENG_Volume_4.png/" },
        { "title": "Jujutsu Kaisen Vol. 5", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/8/89/ENG_Volume_5.png/" },
        { "title": "Jujutsu Kaisen Vol. 6", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/2/25/ENG_Volume_6.png/" },
        { "title": "Jujutsu Kaisen Vol. 7", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/3/3a/ENG_Volume_7.png/" },
        { "title": "Jujutsu Kaisen Vol. 8", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/1/12/ENG_Volume_8.png/" },
        { "title": "Jujutsu Kaisen Vol. 9", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/8/87/ENG_Volume_9.png/" },
        { "title": "Jujutsu Kaisen Vol. 10", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/f/f2/ENG_Volume_10.png/" },
        { "title": "Jujutsu Kaisen Vol. 11", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/a/a4/ENG_Volume_11.png/" },
        { "title": "Jujutsu Kaisen Vol. 12", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/6/66/ENG_Volume_12.png/" },
        { "title": "Jujutsu Kaisen Vol. 13", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/5/58/ENG_Volume_13.png/" },
        { "title": "Jujutsu Kaisen Vol. 14", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/d/d5/ENG_Volume_14.png/" },
        { "title": "Jujutsu Kaisen Vol. 15", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/1/16/ENG_Volume_15.png/" },
        { "title": "Jujutsu Kaisen Vol. 16", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/5/54/ENG_Volume_16.png/" },
        { "title": "Jujutsu Kaisen Vol. 17", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/e/e6/ENG_Volume_17.png/" },
        { "title": "Jujutsu Kaisen Vol. 18", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/8/8d/ENG_Volume_18.png/" },
        { "title": "Jujutsu Kaisen Vol. 19", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/8/8d/ENG_Volume_19.png/" },
        { "title": "Jujutsu Kaisen Vol. 20", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/2/2e/ENG_Volume_20.png/" },
        { "title": "Jujutsu Kaisen Vol. 21", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/3/34/ENG_Volume_21.png/" },
        { "title": "Jujutsu Kaisen Vol. 22", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/c/c0/ENG_Volume_22.png/" },
        { "title": "Jujutsu Kaisen Vol. 23", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/5/5d/Volume_23.png/" },
        { "title": "Jujutsu Kaisen Vol. 24", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/6/6a/Volume_24.png/" },
        { "title": "Jujutsu Kaisen Vol. 25", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/e/ef/Volume_25.png/" },
        { "title": "Jujutsu Kaisen Vol. 26", "author": "Gege Akutami, Ballad Kitaguni", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/jujutsu-kaisen/images/0/00/Volume_26.png/" },
        { "title": "Heavenly Delusion Vol. 1", "author": "Masakazu Ishiguro", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/heavenly-delusion/images/2/2b/Vol1.png/" },
        { "title": "Heavenly Delusion Vol. 2", "author": "Masakazu Ishiguro", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/heavenly-delusion/images/c/ca/Vol2.png/" },
        { "title": "Heavenly Delusion Vol. 3", "author": "Masakazu Ishiguro", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/heavenly-delusion/images/e/e1/Vol3.png/" },
        { "title": "Heavenly Delusion Vol. 4", "author": "Masakazu Ishiguro", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/heavenly-delusion/images/c/cd/Vol4NA.png/" },
        { "title": "Heavenly Delusion Vol. 5", "author": "Masakazu Ishiguro", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/heavenly-delusion/images/4/41/Vol5.png/" },
        { "title": "Heavenly Delusion Vol. 6", "author": "Masakazu Ishiguro", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/heavenly-delusion/images/d/d0/Vol6.png/" },
        { "title": "Heavenly Delusion Vol. 7", "author": "Masakazu Ishiguro", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/heavenly-delusion/images/9/96/Vol7JA.png/" },
        { "title": "Heavenly Delusion Vol. 8", "author": "Masakazu Ishiguro", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/heavenly-delusion/images/1/16/Vol8JA.png/" },
        { "title": "Heavenly Delusion Vol. 9", "author": "Masakazu Ishiguro", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/heavenly-delusion/images/2/2e/Vol9JA.jpg/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 1", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/4/4d/Kimetsu_no_Yaiba_V1_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 2", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/e/e4/Kimetsu_no_Yaiba_V2_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 3", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/a/aa/Kimetsu_no_Yaiba_V3_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 4", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/4/41/Kimetsu_no_Yaiba_V4_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 5", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/e/e0/Kimetsu_no_Yaiba_V5_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 6", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/c/cd/Kimetsu_no_Yaiba_V6_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 7", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/d/d7/Kimetsu_no_Yaiba_V7_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 8", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/0/00/Kimetsu_no_Yaiba_V8_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 9", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/0/01/Kimetsu_no_Yaiba_V9_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 10", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/b/b1/Kimetsu_no_Yaiba_V10_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 11", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/4/49/Kimetsu_no_Yaiba_V11_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 12", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/2/27/Kimetsu_no_Yaiba_V12_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 13", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/3/3a/Kimetsu_no_Yaiba_V13_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 14", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/5/5a/Kimetsu_no_Yaiba_V14_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 15", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/8/8e/Kimetsu_no_Yaiba_V15_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 16", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/b/b3/Kimetsu_no_Yaiba_V16_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 17", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/5/5c/Kimetsu_no_Yaiba_V17_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 18", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/f/fa/Kimetsu_no_Yaiba_V18_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 19", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/e/e7/Kimetsu_no_Yaiba_V19_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 20", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/5/52/Kimetsu_no_Yaiba_V20_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 21", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/2/29/Kimetsu_no_Yaiba_V21_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 22", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/9/98/Kimetsu_no_Yaiba_V22_EN.png/" },
        { "title": "Demon Slayer: Kimetsu no Yaiba Vol. 23", "author": "Koyoharu Gotouge", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/5/58/Kimetsu_no_Yaiba_V23_EN.png/" },
        { "title": "Chainsaw Man Vol. 1", "author": "Tatsuki Fujimoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/chainsaw-man/images/0/0f/Volume_01.png/" },
        { "title": "Chainsaw Man Vol. 2", "author": "Tatsuki Fujimoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/chainsaw-man/images/6/68/Volume_02.png/" },
        { "title": "Chainsaw Man Vol. 3", "author": "Tatsuki Fujimoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/chainsaw-man/images/5/5c/Volume_03.png/" },
        { "title": "Chainsaw Man Vol. 4", "author": "Tatsuki Fujimoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/chainsaw-man/images/e/ef/Volume_04.png/" },
        { "title": "Chainsaw Man Vol. 5", "author": "Tatsuki Fujimoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/chainsaw-man/images/c/cf/Volume_05.png/" },
        { "title": "Chainsaw Man Vol. 6", "author": "Tatsuki Fujimoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/chainsaw-man/images/2/2e/Volume_06.png/" },
        { "title": "Chainsaw Man Vol. 7", "author": "Tatsuki Fujimoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/chainsaw-man/images/3/36/Volume_07.png/" },
        { "title": "Chainsaw Man Vol. 8", "author": "Tatsuki Fujimoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/chainsaw-man/images/1/14/Volume_08.png/" },
        { "title": "Chainsaw Man Vol. 9", "author": "Tatsuki Fujimoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/chainsaw-man/images/f/f3/Volume_09.png/" },
        { "title": "Chainsaw Man Vol. 10", "author": "Tatsuki Fujimoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/chainsaw-man/images/6/6b/Volume_10.png/" },
        { "title": "Chainsaw Man Vol. 11", "author": "Tatsuki Fujimoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/chainsaw-man/images/1/1b/Volume_11.png/" },
        { "title": "Chainsaw Man Vol. 12", "author": "Tatsuki Fujimoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/chainsaw-man/images/4/4e/Volume_12.png/" },
        { "title": "Chainsaw Man Vol. 13", "author": "Tatsuki Fujimoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/chainsaw-man/images/b/b6/Volume_13.png/" },
        { "title": "Chainsaw Man Vol. 14", "author": "Tatsuki Fujimoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/chainsaw-man/images/1/17/Volume_14.png/" },
        { "title": "Chainsaw Man Vol. 15", "author": "Tatsuki Fujimoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/chainsaw-man/images/4/4e/Volume_15.png/" },
        { "title": "Chainsaw Man Vol. 16", "author": "Tatsuki Fujimoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/chainsaw-man/images/4/45/Volume_16.png/" },
        { "title": "Chainsaw Man Vol. 17", "author": "Tatsuki Fujimoto", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/chainsaw-man/images/6/64/Volume_17.png/" },
        { "title": "Oyasumi Punpun Vol. 1", "author": "Inio Asano", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/punpun/images/1/16/Volume1_flat_french.jpg/" },
        { "title": "Oyasumi Punpun Vol. 2", "author": "Inio Asano", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/punpun/images/c/ca/Volume2.png/" },
        { "title": "Oyasumi Punpun Vol. 3", "author": "Inio Asano", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/punpun/images/6/64/Volume3_flat_italian.jpg/" },
        { "title": "Oyasumi Punpun Vol. 4", "author": "Inio Asano", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/punpun/images/0/00/Volume4_flat_french.jpg/" },
        { "title": "Oyasumi Punpun Vol. 5", "author": "Inio Asano", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/punpun/images/0/0d/Volume5_flat_french.jpg/" },
        { "title": "Oyasumi Punpun Vol. 6", "author": "Inio Asano", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/punpun/images/f/f5/Volume6_flat_french.jpg/" },
        { "title": "Oyasumi Punpun Vol. 7", "author": "Inio Asano", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/punpun/images/d/d7/Volume7_flat_french.jpg/" },
        { "title": "Oyasumi Punpun Vol. 8", "author": "Inio Asano", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/punpun/images/1/18/Volume8_flat_french.jpg/" },
        { "title": "Oyasumi Punpun Vol. 9", "author": "Inio Asano", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/punpun/images/1/11/Volume9_flat.jpg/" },
        { "title": "Oyasumi Punpun Vol. 10", "author": "Inio Asano", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/punpun/images/5/56/Volume10_flat.jpg/" },
        { "title": "Oyasumi Punpun Vol. 11", "author": "Inio Asano", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/punpun/images/d/d3/Volume11_flat_french.jpg/" },
        { "title": "Oyasumi Punpun Vol. 12", "author": "Inio Asano", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/punpun/images/1/15/Volume12_flat.jpg/" },
        { "title": "Oyasumi Punpun Vol. 13", "author": "Inio Asano", "price": "$7.50", "imgsrc": "https://static.wikia.nocookie.net/punpun/images/3/30/Volume13.jpg/" }
    ]
}